services:
  airflow:
    build: .
    container_name: airflow
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./logs:/opt/airflow/logs
      - ./db:/opt/airflow/db
      - ./simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    ports:
      - "6070:8080"
    restart: unless-stopped
